services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql/
    networks:
      - inception
    ports:
      - "3306:3306"
    init: true
    restart: on-failure
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: FILE=/run/secrets/mysql_root_password
    env_file:
      - .env
    secrets:
      - db_password
      - mysql_password
      - mysql_root_password
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/html/www/
    networks:
      - inception
    ports:
      - "443:443"
    init: true
    restart: on-failure
    env_file:
      - .env
    # secrets:
    #   - mysql_password
    #   - mysql_root_password
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/html/www/
    networks:
      - inception
    ports:
      - "9000:9000"
    init: true
    restart: on-failure
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
    env_file:
      - .env
    secrets:
      - db_password
      - wp_user_password
      - wp_admin_password
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/bde-sous/data/mariadb_data
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/bde-sous/data/wordpress_data
      o: bind

networks:
  inception:
    name: inception
    driver: bridge

secrets:
  db_password:
    file: ../secrets/DB_PASSWORD.txt
  mysql_password:
    file: ../secrets/MYSQL_PASSWORD.txt
  mysql_root_password:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  wp_admin_password:
    file: ../secrets/WP_ADMIN_PASSWORD.txt
  wp_user_password:
    file: ../secrets/WP_USER_PASSWORD.txt


