services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql/
    networks:
      - inception
    ports:
      - "3306:3306"
    init: true
    restart: on-failure
    env_file:
      - ./mariadb/.env
  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx
    volumes:
      - wordpress_data:/var/html/www/
    networks:
      - inception
    ports:
      - "443:443"
    init: true
    restart: on-failure
    env_file:
      - ./nginx/.env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./wordpress
    volumes:
      - wordpress_data:/var/html/www/
    networks:
      - inception
    ports:
      - "9000:9000"
    init: true
    restart: on-failure
    env_file:
      - ./wordpress/.env
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/bde-sous/data/mariadb_data
      o: bind
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/bde-sous/data/wordpress_data
      o: bind

networks:
  inception:
    driver: bridge
