services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    volumes:
      - ~/inception/database:/var/lib/mysql/:rw
    networks:
      - inception
    ports:
      - "3306:3306"
    init: true
    restart: on-failure
    env_file:
      - ./mariadb/.env
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ~/inception/wordpress:/var/html/www/:rw
    networks:
      - inception
    ports:
      - "443:443"
    init: true
    restart: on-failure
    env_file:
      - ./nginx/.env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./wordpress
    volumes:
      - ~/inception/wordpress:/var/html/www/:rw
    networks:
      - inception
    ports:
      - "9000:9000"
    init: true
    restart: on-failure
    env_file:
      - ./wordpress/.env
    depends_on:
      - mariadb

# volumes:
#   database:
#     name: database
#     driver: local
#     driver_opts:
#       type: none
#       device: ~/inception/database
#       target: /var/lib/mysql/

networks:
  inception:
    driver: bridge
